# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Bookish Potato"
weight = 2

[ko]
languageName = "Korean"
languagedirection = "ltr"
title = "책을 좋아하는 감자"
weight = 1